title: Raghad Alotaibi <br> # your name (or website title) here
logo: "/images/Untitled171 2.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <b>About me </b> <br>
  I graduated with a Master's degree in Data Analytics from DCU and a Bachelor's degree in Computer Science from PNU 
  with strong technical knowledge in data processing and analysis through computer programming languages including Python and R.
  <br><br>
  I have experince in applying machine learning algorithms to different problems through data science projects that are demonstrated in this portfolio. 
  <br><br>
  
  <a href="https://www.linkedin.com/in/raghad-alotaibi7/">View My LinkedIn Profile</a> 

  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
